[package]
name = "rfs_server"
version = "0.1.0"
authors = ["Martin Vassor <martin.vassor@epfl.ch>"]

[dependencies]
generic-array = "0.5.1"
base64 = "0.6.0"
blowfish = "0.2.1"
block-cipher-trait = "0.2.0"
rand = "0.3"
log = "*"
env_logger = "0.4"
