[package]
name = "rfs_client"
version = "0.1.0"
authors = ["Martin Vassor <martin.vassor@epfl.ch>"]

[dependencies]
base64 = "0.6.0"
log = "*"
env_logger = "*"
blowfish = "0.2.1"
block-cipher-trait = "0.2.0"
generic-array = "0.5.1"
bincode = "*"
serde_derive = "*"
serde = "*"
